name: 'Git-Crypt Unlock'

author: 'Danstan Onyango - Zemuldo'

description: 'Action to Unlock files encrypted using Git-Crypt, supports keys with passphrase'

branding:
  icon: 'unlock'  
  color: 'green'

runs:
  using: node12
  pre: dist/build/index.js
  pre-if: '$GITHUB_REPOSITORY == zemuldo/git-crypt-unlock'
  main: dist/run/index.js